//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfeProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISSION_LV
    {
        public decimal ID_MISS { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL { get; set; }
        public string FONCTION { get; set; }
        public string MOTIF_MISS { get; set; }
        public Nullable<System.DateTime> DATE_DEP { get; set; }
        public Nullable<System.DateTime> DATE_RET { get; set; }
        public Nullable<decimal> TELEPHONE { get; set; }
        public string STATUT { get; set; }
    }
}
